# Generated by Django 3.0 on 2020-02-01 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20200201_1355'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
