# Generated by Django 3.0 on 2020-01-30 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Config', '0002_auto_20200130_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appSite', models.CharField(blank=True, choices=[('Prod', 'PROD'), ('Cob', 'COB')], help_text='Choose App Site', max_length=4)),
                ('Primary', models.BooleanField(default=True)),
                ('hostName', models.CharField(max_length=30)),
                ('dnsName', models.CharField(max_length=100)),
                ('appName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Config.Application')),
            ],
        ),
    ]
