# Generated by Django 3.0 on 2020-01-31 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Config', '0005_auto_20200131_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Name_CC', models.CharField(max_length=2)),
                ('cntry_cde', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300)),
                ('Countires', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Config.Countries')),
            ],
        ),
        migrations.RemoveField(
            model_name='application',
            name='choices',
        ),
        migrations.DeleteModel(
            name='Choices',
        ),
    ]
