# Generated by Django 3.0 on 2020-01-31 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Config', '0006_auto_20200131_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regions',
            name='Countires',
        ),
        migrations.AddField(
            model_name='countries',
            name='Region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Config.Regions'),
        ),
    ]
