# Generated by Django 3.0 on 2020-01-31 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Config', '0007_auto_20200131_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='AppRegion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Config.Regions'),
        ),
    ]
