# Generated by Django 3.0 on 2020-01-31 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Config', '0009_auto_20200131_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='AppCountries',
            field=models.ManyToManyField(to='Config.Countries'),
        ),
        migrations.AlterField(
            model_name='application',
            name='AppRegion',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='countries',
            name='Region',
            field=models.CharField(max_length=5),
        ),
        migrations.DeleteModel(
            name='Regions',
        ),
    ]
