# Generated by Django 3.0 on 2020-02-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Config', '0010_auto_20200131_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countries',
            name='id',
        ),
        migrations.AlterField(
            model_name='countries',
            name='Name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='countries',
            name='Name_CC',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='countries',
            name='Region',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='countries',
            name='cntry_cde',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
