# Generated by Django 3.0 on 2020-02-07 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Config', '0011_auto_20200207_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='AppCountries',
        ),
        migrations.AddField(
            model_name='application',
            name='AppCountries',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Config.Countries'),
        ),
    ]
