# Generated by Django 3.0 on 2020-02-07 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Config', '0012_auto_20200207_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='AppCountries',
        ),
        migrations.RemoveField(
            model_name='serverconfig',
            name='appName',
        ),
    ]
