# Generated by Django 3.0 on 2020-02-07 13:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Config', '0013_auto_20200207_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='countries',
            name='id',
            field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serverconfig',
            name='appName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Config.Application'),
        ),
        migrations.AlterField(
            model_name='countries',
            name='Name',
            field=models.CharField(max_length=20),
        ),
    ]
